import pandas as pd
import matplotlib.pyplot as plt
df=pd.read_csv("C:\\Users\\acer\\Desktop\\student.csv")
print(df)
plt.bar(df['Period'],df['Region'])
plt.xlabel('X-axis label')
plt.ylabel('Y-axis label')
plt.title('Bar Plot')
plt.show()
plt.stem(df['Count'],df['Region'],)
plt.xlabel('X-axis label')
plt.ylabel('Y-axis label')
plt.title('stem Plot')
plt.show()
plt.stackplot(df['Count'],df['Region'])
plt.xlabel('X-axis label')
plt.ylabel('Y-axis label')
plt.title('stackplot Plot')
plt.show()
plt.scatter(df['Period'],df['Count'])
plt.xlabel('X-axis label')
plt.ylabel('Y-axis label')
plt.title('scatter Plot')
plt.show()
plt.hist(df['Period'],weights=df['Count'])
plt.xlabel('X-axis label')
plt.ylabel('Y-axis label')
plt.title('histogram Plot')
plt.show()

